Adviser workflow notebook
thoth-station/notebooks pull request #57
Opened 2020-01-03 21:59 UTC by pacospace

Signed-off-by: Francesco Murdaca <fmurdaca@redhat.com>

2020-01-06 09:01 UTC, CermakM commented on notebooks/workflows/adviser-inspection-workflow.ipynb
> +{
<p>"stable" should be uppercase</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/thoth-station/notebooks/pull/57/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2020-01-07 09:02 UTC, CermakM commented on notebooks/workflows/adviser-inspection-workflow.ipynb
> +{
<p><code>json</code></p><p><code>&nbsp;&nbsp;"THOTH_ADVISER_LIBRARY_USAGE": {</code></p><p><code>&nbsp;&nbsp;&nbsp;&nbsp;"report": {},</code></p><p><code>&nbsp;&nbsp;&nbsp;&nbsp;"version": "string"</code></p><p><code>&nbsp;&nbsp;},</code></p><p> </p><p> </p><p>should be string, not an object</p><p> </p><p><code>json</code></p><p><code>"THOTH_ADVISER_LIBRARY_USAGE": "{ \"report\": {}, \"version\": \"string\" }",</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/thoth-station/notebooks/pull/57/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2020-01-07 09:02 UTC, CermakM requested changes
See the comments

2020-01-07 11:09 UTC, CermakM commented
@pacospace I think we should submit the notebook without outputs, WDYT?

2020-01-07 11:30 UTC, pacospace commented
> @pacospace I think we should submit the notebook without outputs, WDYT?

Updated, thanks :)

2020-01-08 14:12 UTC, CermakM approved these changes

2020-01-08 15:47 UTC, merged